version: '3.8'

services:
  frontend:
    image: ihl-harbor.apps.innovate.sg-cna.com/community-defender-ai/frontend:v7
    build:
      context: ./community-defender-fe
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - transcription-service
      - summarization-service
      - identification-service

  transcription-service:
    image: ihl-harbor.apps.innovate.sg-cna.com/community-defender-ai/transcription-service:v7
    build:
      context: ./transcription-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  summarization-service:
    image: ihl-harbor.apps.innovate.sg-cna.com/community-defender-ai/summarization-service:v7
    build:
      context: ./summarization-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - app-network

  identification-service:
    image: ihl-harbor.apps.innovate.sg-cna.com/community-defender-ai/identification-service:v7
    build:
      context: ./identification-service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
