transcript = ["911, what's your emergency?","Hi, I need help! There's been a car accident on Maple Street.",
"Okay, I understand. Are you or anyone else injured?", 
"Yes, there's a woman who looks seriously hurt. She's not responding.",
"I'm dispatching emergency services to your location. Can you tell me if she's breathing?",
"I'm not sure. I don't think she is.",
"Alright, can you check her pulse or see if her chest is moving?",
"Hold on... No, I don't see any movement. What should I do?",
"Stay calm. Help is on the way. Do you know CPR?",
"Yes, but it's been a while since I learned.",
"That's okay. I can guide you through it. First, tilt her head back slightly to open her airway."]